CHROMIUM: drm/nouveau: Prevent inlining of ramfuc_reg
Apparently when gcc inlines it, it eats up 16 bytes on the stack every
time. Eventually we hit errors because our stack grew too much:
ramnve0.c:1383:1: error: the frame size of 1496 bytes is larger than 1024 bytes
We fix this by preventing inlining for this function.

BUG=chromium:387296
TEST=nouveau compiles on ARM

Change-Id: Ie5d58727c7f9dd6bfd7da89606bd89809dd127b3
Reviewed-on: https://chromium-review.googlesource.com/208994
Tested-by: Stéphane Marchesin <marcheu@chromium.org>
Reviewed-by: Sean Paul <seanpaul@chromium.org>
Commit-Queue: Stéphane Marchesin <marcheu@chromium.org>